import React from 'react';
import { Link } from 'react-router-dom';
import './Blog.css';

const Blog = () => {
  const blogPosts = [
    {
      id: 1,
      title: 'Code AI Checker Free: Detect AI-Generated Code Instantly',
      excerpt: 'Learn how to use our free AI code detector to identify whether code was written by humans or generated by AI models like ChatGPT, GitHub Copilot, and more.',
      date: 'January 15, 2025',
      category: 'Tutorial',
      keywords: 'code ai checker free, ai code detector, free code analysis'
    },
    {
      id: 2,
      title: 'ChatGPT Code AI Checker: How to Verify AI-Generated Code',
      excerpt: 'Discover how to detect code generated by ChatGPT and other AI models. Understand the patterns and characteristics that indicate AI generation.',
      date: 'January 10, 2025',
      category: 'Guide',
      keywords: 'chatgpt code ai checker, detect chatgpt code, ai code verification'
    },
    {
      id: 3,
      title: 'Code Plagiarism AI Checker: Ensure Originality in Your Projects',
      excerpt: 'Protect your codebase from plagiarism and ensure originality. Learn how our AI-powered plagiarism detection works alongside code analysis.',
      date: 'January 5, 2025',
      category: 'Security',
      keywords: 'code plagiarism ai checker, code originality, plagiarism detection'
    },
    {
      id: 4,
      title: 'AI Code Detector: Understanding Detection Accuracy and Methods',
      excerpt: 'Deep dive into how AI code detection works, what factors influence accuracy, and how to interpret detection results effectively.',
      date: 'December 28, 2024',
      category: 'Technical',
      keywords: 'ai code detector, code detection accuracy, ai detection methods'
    },
    {
      id: 5,
      title: 'Detect AI Generated Code: Best Practices and Tips',
      excerpt: 'Practical tips and best practices for using AI code detection tools effectively. Learn when and how to analyze code for AI generation.',
      date: 'December 20, 2024',
      category: 'Best Practices',
      keywords: 'detect ai generated code, code analysis tips, ai detection best practices'
    },
    {
      id: 6,
      title: 'Code Originality Checker: Why It Matters in Modern Development',
      excerpt: 'Explore the importance of code originality in software development and how AI-powered tools help maintain code quality and authenticity.',
      date: 'December 15, 2024',
      category: 'Industry',
      keywords: 'code originality checker, code authenticity, software development quality'
    }
  ];

  return (
    <div className="blog">
      <section className="hero-section">
        <div className="container">
          <h1 className="page-title">Blog</h1>
          <p className="page-subtitle">
            Insights, guides, and updates about AI code detection and software development
          </p>
        </div>
      </section>

      <section className="blog-section">
        <div className="container">
          <div className="blog-grid">
            {blogPosts.map((post) => (
              <article key={post.id} className="blog-card fade-in">
                <div className="blog-card-header">
                  <span className="blog-category">{post.category}</span>
                  <span className="blog-date">{post.date}</span>
                </div>
                <h2 className="blog-title">{post.title}</h2>
                <p className="blog-excerpt">{post.excerpt}</p>
                <div className="blog-footer">
                  <Link to={`/blog/${post.id}`} className="blog-read-more">
                    Read More →
                  </Link>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="cta-section">
        <div className="container">
          <div className="cta-box">
            <h2 className="cta-title">Ready to Check Your Code?</h2>
            <p className="cta-text">
              Try our free AI code detector and get instant analysis results
            </p>
            <Link to="/" className="btn btn-primary btn-large">
              Check Code Now
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Blog;
