import React from 'react';
import './HowItWorks.css';

const HowItWorks = () => {
  const steps = [
    {
      number: 1,
      title: 'Paste Your Code',
      description: 'Simply paste your code snippet into our input box. We support multiple programming languages including Python, JavaScript, Java, C++, PHP, HTML, CSS, MATLAB, and more.',
      icon: '📋'
    },
    {
      number: 2,
      title: 'AI Analysis',
      description: 'Our advanced AI algorithm analyzes the code structure, patterns, variable naming, formatting consistency, and other characteristics to identify AI-generated code signatures.',
      icon: '🤖'
    },
    {
      number: 3,
      title: 'Pattern Detection',
      description: 'The system examines repetitive patterns, formatting uniformity, complexity metrics, and coding style to determine the likelihood of AI generation.',
      icon: '🔍'
    },
    {
      number: 4,
      title: 'Get Results',
      description: 'Receive a detailed analysis report with confidence percentage, explanation of findings, key indicators, and originality score. Export or share results easily.',
      icon: '📊'
    }
  ];

  return (
    <div className="how-it-works">
      <section className="hero-section">
        <div className="container">
          <h1 className="page-title">How It Works</h1>
          <p className="page-subtitle">
            Understand how our AI-powered code detection system analyzes and identifies AI-generated code
          </p>
        </div>
      </section>

      <section className="steps-section">
        <div className="container">
          <div className="steps-grid">
            {steps.map((step, index) => (
              <div key={index} className="step-card fade-in" style={{ animationDelay: `${index * 0.1}s` }}>
                <div className="step-number">{step.number}</div>
                <div className="step-icon">{step.icon}</div>
                <h3 className="step-title">{step.title}</h3>
                <p className="step-description">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="details-section">
        <div className="container">
          <div className="details-content">
            <h2 className="details-title">What We Analyze</h2>
            
            <div className="analysis-features">
              <div className="analysis-feature">
                <h4 className="feature-heading">Code Structure</h4>
                <p className="feature-text">
                  We examine the overall structure and organization of your code, looking for patterns 
                  that are characteristic of AI-generated code versus human-written code.
                </p>
              </div>

              <div className="analysis-feature">
                <h4 className="feature-heading">Variable Naming</h4>
                <p className="feature-text">
                  AI models often use generic or predictable variable names. We analyze naming patterns 
                  to identify this characteristic.
                </p>
              </div>

              <div className="analysis-feature">
                <h4 className="feature-heading">Formatting Consistency</h4>
                <p className="feature-text">
                  AI-generated code typically has extremely uniform formatting. We measure consistency 
                  levels to detect this pattern.
                </p>
              </div>

              <div className="analysis-feature">
                <h4 className="feature-heading">Code Complexity</h4>
                <p className="feature-text">
                  We analyze the complexity-to-length ratio, as AI-generated code often has different 
                  complexity patterns compared to human-written code.
                </p>
              </div>

              <div className="analysis-feature">
                <h4 className="feature-heading">Repetitive Patterns</h4>
                <p className="feature-text">
                  AI models sometimes generate repetitive code structures. We detect these patterns 
                  to identify potential AI generation.
                </p>
              </div>

              <div className="analysis-feature">
                <h4 className="feature-heading">Comment Patterns</h4>
                <p className="feature-text">
                  The presence, absence, or style of comments can indicate whether code was written 
                  by a human developer or generated by AI.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="cta-section">
        <div className="container">
          <div className="cta-box">
            <h2 className="cta-title">Ready to Check Your Code?</h2>
            <p className="cta-text">
              Try our free AI code detector now and get instant results
            </p>
            <a href="/" className="btn btn-primary btn-large">
              Check Code Now
            </a>
          </div>
        </div>
      </section>
    </div>
  );
};

export default HowItWorks;
